default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chatterapp_development

test:
  <<: *default
  database: chatterapp_test

production:
  <<: *default
  database: chatterapp_production
  username: chatterapp
  password: <%= ENV['CHATTERAPP_DATABASE_PASSWORD'] %>
